### ISSUE TITLE
Can't Widen Wordlist Column

### ISSUE THREAD

**Issue by Steve-Miller** [sillsdev/cog#30]
Hi Damien. Thanks for doing this project.

In the Input tab, Word lists, there is the Word lists table. The header of each column has a single meaning. I can hover over the divider between columns, and the cursor changes into a double-headed horizontal arrow, indicating that I can widen the column. That's what I want, because some of the meanings are too wide right now, and I can't tell the difference between a couple of them. So I click and hold to widen the column. The column won't widen for me.

If you need me to add a screen shot, let me know.

**Comment by ddaspit** [comment]
Thanks for trying out Cog. Which version are you using? This was an issue that was fixed in 1.1.1, which is the latest version.

**Comment by Steve-Miller** [comment]
I got v. 1.1.0. not more than a month ago.

Thanks again for working on this. I have an intricate language/dialect 
situation here I'm trying to sort out.

Steve

**Comment by ddaspit** [comment]
Yeah, I released 1.1.1 not too long ago. Let me know if you need any more help.
