### ISSUE TITLE
Nonexistant Words

### ISSUE THREAD

**Issue by Steve-Miller** [sillsdev/cog#36]
This is more a question than an issue, I suspect, but it could turn into one or more issues. I don't have your email address anymore, nor could I find a way to contact you here, so I couldn't ask this off-line.

In certain cases, one variety has a word, but the other doesn't. For example, one variety has pronouns for first-person-singular-masculine and first-person-singular-feminine. It does not have a generic first-person-singular that both men and women use. In contrast, the other variety recognizes a generic first-person-singular only. It does not distinguish whether a man or a woman is speaking. This is a major contrast, but I'm not sure how to designate it in Cog. Leave it blank?

In other cases, I don't have a word in one variety. The language most likely does have the word, but the recording wasn't clear, or maybe the collector simply forgot to ask it in one variety. I don't want Cog flagging this as a major contrast like I would in the pronoun example above. How do I differentiate between a missing word and a non-existent word?

**Comment by ddaspit** [comment]
The "Contact" link on the Cog [webpage](http://sillsdev.github.io/cog/) will get you my email address.

If a word is blank, Cog will ignore it when comparing two varieties. It will not be counted in the lexical similarity computation. This would be a good way to deal with the scenario where a word was accidentally not collected for a variety.

The first case where there are different masculine and feminine forms of the word is a little trickier. Cog supports the ability to specify multiple words for a meaning separated by commas. When comparing two varieties, Cog will choose the words that are the most phonetically similar to compare. Using this capability, you could specify both the masculine and feminine forms of the pronoun under the generic first-person-singular meaning. The other possibility is to keep it in separate masculine and feminine meanings and leave the generic meaning blank. This way the pronoun would be ignored in cases where one variety only specifies a generic pronoun and the other variety specifies masculine and feminine pronouns. It is really up to you how you want to deal with it.

**Comment by ddaspit** [comment]
Let me know if my suggestions fill your needs or if anything needs to be added to Cog for this issue.

**Comment by Steve-Miller** [comment]
I've been waiting to understand the tool a little more before responding. But if I understand your suggestions correctly, I don't think either of your suggestions work correctly.

The pronoun scenario is a little intricate, so I'll try something simpler first. It turns out that one of the varieties I'm looking at doesn't have a word for 'blue'. It has words for other colors, just not one for the color blue. Alright, lets use this as a base for another scenario. Suppose we have three varieties. The collector did her job and asked for the word "blue" in all three. Two varieties gave her a word for "blue", but the third simply does not have a word for the color, so she left it blank:

A: blu
B: balu
C:

Now Cog compares the words for varieties A and B and calculates the similarities. However, when Cog compares A and C, and B and C, it will ignore the pairing. It seems to me that this is not accurate and will skew the results. Instead of ignoring the pairings, it should compare them and flag them as 0% cognate similarity.

In other cases, the collector elicited a response but not in another, for whatever reason. This word is left blank in one or more varieties. Cog rightly ignores the blank pairings.

Therefore, a blank in Cog has a double meaning. In one case, there simply is no word in the variety, and we know that now. In the other, the word was not elicited for one or more varieties and the data is unknown. If this was a SQL database, I would mark the former as blank and the latter as NULL.

For now, I have put the IPA stress mark ˈ in varieties that simply do not have a word for "blue." I'm hoping that will tell Cog that there is no cognate whatsoever in variety C, and that it is 100% lexically dissimilar from a variety that does. I don't know the tool well enough to check just yet.

In any case, using a stress mark this way feels very much like a kludge, and I'm hoping for a better solution. I'm flying out to the village next week, so I've not had much chance of thinking of an alternate solution to suggest.

**Comment by ddaspit** [comment]
Unfortunately, there isn't a setting to change the behavior of how it compares blank words. I experimented a bit and found that if you insert the syllable break marker (a period), then Cog will include the word in the comparison. I think that should give you what you want.

**Comment by Steve-Miller** [comment]
I don't think a setting for evaluating blank words is the answer, because I have both kinds of data in the same data set. I need a way for Cog to evaluate both kinds.

I'll check the syllable break mark (a period) when I get a chance. It seems to be very much the same kind of solution as the stress mark I've been using. It may work for now, but it would be nice to have some other solution. I still haven't had time to think about alternative solutions, as I've been just a little bit busy in a translation workshop. At the very least, using a period for this sort of thing ought to be documented (if that's the final answer).

**Comment by ddaspit** [comment]
I am going to go ahead and close this issue, since using the syllable break marker should fill this need.

**Comment by Steve-Miller** [comment]
Since this is the solution you're going with, it would be nice to have it documented somewhere.
