### ISSUE TITLE
Add a New Meaning Dialog Broken

### ISSUE THREAD

**Issue by Steve-Miller** [sillsdev/cog#38]
v.1.2.0.10002 (10/13/2015)
I click on Add a new Meaning. The dialog comes up. I add a gloss and a category. Whether I click on OK or tab over to the OK button and hit enter, nothing happens. I can't add a new meaning. All I can do is Cancel the dialog.

**Comment by ddaspit** [comment]
Thanks for the heads up. I fixed this and pushed out a new release, 1.2.1.
