### ISSUE TITLE
Other possible auto syllabification issues

### ISSUE THREAD

**Issue by Steve-Miller** [sillsdev/cog#50]
The automatic syllabification feature is nice. But it seems to be missing some easy breaks, and I haven't been able to determine why. (Either that, or I'm misunderstanding what | is supposed to signify.) Some seem to have to do with the glottal stop, and others with the stress marker, but I haven't found a pattern to it yet. Some examples from Input / Varieties / Wordsː

'bi|ta
'?|u.ru
|mamaː˦ ˨|
|'ka|mi
|ɾuɾu'naʲ˦|

**Comment by ddaspit** [comment]
The bar character (|) is used to mark the stem. Cog will only use the stem when comparing and ignore the prefix and suffix. In IPA, syllable breaks are marked using the period character (.). If you look in the Varieties view, you will see that Cog has inserted gray syllable break markers to show how it has syllabified a word. If there is already a boundary marker of some type at the syllable break (e.g. a stress marker), Cog will not bother to add the syllable break marker.

If a word already contains syllable breaks, Cog will not attempt to syllabify it. Cog will also recognize tone letters as syllable breaks. In other words, Cog will not syllabify a word if it contains a period or tone letter character in it. If all of the syllable breaks are not specified in these words, you will need to add them manually. I hope that clarifies what is happening.

**Comment by Steve-Miller** [comment]
It does clarify. Thanks.

I went through the doc before writing this up. I don't think there's 
anything there explaining this. If it's not there or hard to find, I 
think I would consider this a documentation bug.
