### ISSUE TITLE
Catastrophic Errorː Settings Crash

### ISSUE THREAD

**Issue by Steve-Miller** [sillsdev/cog#51]
I can't give you exact steps to reproduce this because Cog is no longer starting for me. When I try to start it, I see a message, "Segmenting and syllabifying words..."  It hangs there.

I had just turned off a setting for syllabification. I think it was combining vowels in the same position into one syllable. I got an error that gave me an option to Quit and send, so you should have an error report in your inbox somewhere.

**Comment by ddaspit** [comment]
Can you download and try out the latest nightly build of Cog to see if it fixes this problem? You can get it here: http://downloads.palaso.org/cog/latest-dev/.

**Comment by Steve-Miller** [comment]
That nightly build allowed me to start up Cog. I was also able to 
uncheck Input / Settings / Combine vowels in the same syllable position. 
Thanks for the quick turn-around.
