### ISSUE TITLE
Combine Vowels Seems to have no effect

### ISSUE THREAD

**Issue by Steve-Miller** [sillsdev/cog#52]
I went to Input / Settings / Syllabification. I unchecked the first box, "Combine vowels in the same syllable position" and clicked on Apply. This seems to have no effect. For example, if I go to Input / Varieties / Words, I find no syllable break in between the 'i' and the 'a' in |'tia|.

I tried exiting the program and coming back in. No change. I even tried rerunning "Compare all variety pairs." Still no change.

**Comment by ddaspit** [comment]
The "Combine vowels in the same syllable position" setting is used to determine whether Cog will group two vowels into a diphthong segment. If you look at 'tia in the Varieties view, you will see that when this setting is checked "ia" is grouped into a single segment, but when this is unchecked "i" and "a" are separated by a space. These means that for comparison and alignment purposes, they are being treated as two separate segments. If you want Cog to break syllables between successive vowels, you will either need to change the "Sonority scale" in the syllabification settings or insert a syllable break manually. If you want more information on changing the "Sonority scale", let me know.

**Comment by Steve-Miller** [comment]
Yeah, I think I found that "Combine vowels" setting shortly after I reported this bug. That particular setting confused me because I was getting mixed up between segmenting and syllabification.
