### ISSUE TITLE
A Pair that should be a cognate but are notː prefix problem, I think.

### ISSUE THREAD

**Issue by Steve-Miller** [sillsdev/cog#54]
See the screen shot:

![cog-non-cognate_cognate](https://cloud.githubusercontent.com/assets/583475/11738629/23e0ad6e-a030-11e5-8006-5d2a99f934f7.jpg)

I have here a word that is identical to another in the cognate list, but nevertheless is listed as a non-cognate. I think at issue is that for Uni (Ramo), Cog still thinks "ʔa" is a prefix.

I did run the stemmer earlier in the project, and it came up with "ʔa" as a prefix. I disagreed, and have since eliminated ʔa as a prefix. However, Cog is persistent, and retained the prefix in the data, when it shouldn't, I don't think. In the .cogx file, I find this lineː

        <Word meaning="lap">ˈʔa.wo.to</Word>

Then further down, I find this lineː

        <Word meaning="lap" stemIndex="3" stemLength="6">ˈʔa.wo.to</Word>

As far as I can tell, this last line became incorrect once I removed the prefix.

This is the same .cogx that has been through a couple of major crashes, so I don't know if that has something to do with it or not.

**Comment by ddaspit** [comment]
If you make any changes to the affixes for a variety, you will need to run the stemmer again. You will want to use the "Only use already specified affixes" option when you run it again.

**Comment by Steve-Miller** [comment]
It makes sense that I would have to run the stemmer again, once you said it. It's just that something like a week passed between working on affixes and looking at the multiple word alignment. Suggestion: In the Input / Varieties / Affixes area, light up an option to rerun the stemmer whenever an affix is added, edited, or deleted.

**Comment by Steve-Miller** [comment]
So I reran the stemmer and went back to Multiple Word Alignment. I looked up the gloss 'lap', the same as I reported above. Nothing there. Just a blank screen. That was a shock. I wanted to yell at Cog, "What did you do to my data?" Another gloss offered up a blank screen, too.

So I took a deep breath and tried to think through what might have caused that. I thought, hmm, I wonder what would happen if I ran "Compare all variety pairs" again? I did, and that appears to have cured my blank screen.

I imagine there are various ways to avoiding more linguist high blood pressure. Maybe a yes/no dialog could come up whenever the stemmer finished: "Would you like to compare all variety pairs again?"

Maybe another thing to do is avoid a blank screen on Multiple Word Alignment. Maybe something like: "If your screen is blank, you might want to compare all variety pairs."

I dunno. You know the software better than I do. I'm just trying to avoid having someone else go through the same surprise I did.

**Comment by Steve-Miller** [comment]
One more note: I was somewhat surprised to see the Bouni (Sumo) word come up as a cognate the first time. The second time, it didn't stay a cognate. I think this makes sense, but bring it up in case it needs to be checked.

**Comment by ddaspit** [comment]
I added text to the multiple word alignment view to prompt the user to compare all variety pairs if a comparison is needed.
