### ISSUE TITLE
Cog won't open in Windows 10 despite reinstallation

### ISSUE THREAD

**Issue by paschawu** [sillsdev/cog#60]
I was working with Cog and suddenly the light was off. Fortunately, I have saved all the necessary data but my Cog software won't open anymore although I have reinstalled and/or repaired the program several times, to the point of downloading the exe file once again. Please tell me how to fix this issue! Thanks b4

**Comment by ddaspit** [comment]
Are you receiving any error messages when you try to open Cog?

**Comment by paschawu** [comment]
Solved already. It turns out to be corrupt SIL folder on C:\...\Program Files. It worked when I tried to re-install it on different folder. Thanks for your kind support, ddaspit :100:

**Comment by ddaspit** [comment]
I'm glad you figured it out. Let me know if you have any more questions.
